# Generated by Django 3.1.1 on 2020-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='Roll_No',
            field=models.IntegerField(),
        ),
    ]
